#te faltará cammbiar la ruta del volumen de mysql , crear los usuarios de mysql y importar correctamente
#el fichero sql 
version: "3"
services:
  db:
    image: mysql:latest
    container_name: foodtrackv4db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d/
    networks:
      - mynet
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: foodtrackv4
  web:
    image: node:latest
    container_name: foodtrackv4
    ports:
      - "3000:3000"
    volumes:
      - volumendespliegues:/var/www/html/storage
    networks:
      - mynet
    depends_on:
      - db
    command: /bin/bash -c "apt-get update && apt-get upgrade -y && apt-get install curl -y  && apt-get install npm -y && npm install -g npm -y &&  apt-get install git -y && git clone https://github.com/borjeta/nuevodespliegue.git && ls -a && cd nuevodespliegue && ls -a && cd foodtrackv4 && cd material-kit-react-main && npm install && npm start"
  api:
    image: php:latest
    container_name: foodtrackv4api
    ports:
      - "8000:8000"
    volumes:
      - volumendespliegues:/var/www/html/storage
    networks:
      - mynet
    depends_on:
      - db
    command: /bin/bash -c  "apt-get update && apt-get upgrade -y && apt-get install curl -y  && apt-get install git -y && git clone https://github.com/borjeta/nuevodespliegue.git && ls -a && cd nuevodespliegue && ls -a  && cd foodtrackv4 && cd api && ls -a && curl -sS https://getcomposer.org/installer -o composer-setup.php &&
     php composer-setup.php && php composer.phar install && php artisan serve"
networks:
  mynet:
    driver: bridge
volumes:
  volumendespliegues:
    driver: local
    driver_opts:
      type: none
      device: /home/foodtrackv4
      o: bind
