version: "3"
services:
  db:
    image: mysql:latest
    container_name: foodtrackv4db
    ports:
      - "3306:3306"
    volumes:
      - volumendespliegue:/var/www/html/storage
    networks:
      - mynet
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: foodtrackv4
  web:
    image: node:latest
    container_name: foodtrackv4
    ports:
      - "3000:3000"
    volumes:
      - volumendespliegue:/var/www/html/storage
    networks:
      - mynet
    depends_on:
      - db
    command: /bin/bash -c "apt-get update && apt-get upgrade -y && apt-get install curl -y  && apt-get install npm -y && npm install -g npm -y &&  apt-get install git -y && git clone https://github.com/borjeta/nuevodespliegue.git && ls -a && cd nuevodespliegue && ls -a && cd foodtrackv4 && cd material-kit-react-main && npm install && npm start"
  api:
    image: ubuntu:latest
    container_name: foodtrackv4api
    ports:
      - "8000:8000"
    volumes:
      - volumendespliegue:/var/www/html/storage
    networks:
      - mynet
    depends_on:
      - db
    # command: /bin/bash -c  "apt-get update -y && apt-get upgrade -y && apt-get install curl -y && apt-get install libapache2-mod-php8.1-y &&apt-get install software-properties-common -y  && add-apt-repository ppa:ondrej/php -y && apt-get update && apt-get upgrade -y && apt install php8.1 -y && apt-get install composer -y && apt-get install npm -y && npm install -g npm -y &&  apt-get install git -y && git clone https://github.com/borjeta/nuevodespliegue.git && ls -a && cd nuevodespliegue && ls -a && cd foodtrackv4 && cd api && apt-get install composer -y && mysql -u root -p foodtrackv4 < foodtrackv4.sql && composer install && php artisan serve"
networks:
  mynet:
    driver: bridge
volumes:
  volumendespliegue:
    driver: local
    driver_opts:
      type: none
      device: /home/foodtrackv4
      o: bind
